---
- name: Allow ports for web server
  hosts: balancer
  tasks:    
  - name: allow http
    become: true
    ufw:
      rule: allow
      port: 80
      proto: tcp
  
  - name: allow https
    become: true
    ufw:
      rule: allow
      port: 443
      proto: tcp
  
  - name: allow port 5000
    become: true
    ufw:
      rule: allow
      port: 5000
      proto: tcp
