---
- name: web-app
  hosts: cloud
  gather_facts: false
  tasks:
    - name: create /www/web folder
      file:
        path: /home/ubuntu/www/web
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: copy web.compose.yml
      copy:
        src: ../files/web.compose.yml
        dest: /home/ubuntu/www/web/web.compose.yml

    - name: copy web folder
      copy:
        src: ../files/web
        dest: /home/ubuntu/www/web
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: run docker compose
      become: yes
      command: docker compose -f /home/ubuntu/www/web/web.compose.yml up -d
      args:
        chdir: /home/ubuntu/www/web